export const APP_LOAD = '@@CONNECT4/APP_LOAD'

export const PLAYER_RENAME = '@@CONNECT4/PLAYER_RENAME'
export const SWITCH_PLAYER = '@@CONNECT4/SWITCH_PLAYER'
export const UPDATE_CASE = '@@CONNECT4/UPDATE_CASE'
export const FINISH = '@@CONNECT4/FINISH'
export const DRAW = '@@CONNECT4/DRAW'

export const DIALOG_OPEN = '@@CONNECT4/DIALOG_OPEN'
export const DIALOG_CLOSE = '@@CONNECT4/DIALOG_CLOSE'

export const JOIN_MULTI = '@@CONNECT4/JOIN_MULTI'
export const MULTIGAME_STARTED = '@@CONNECT4/MULTIGAME_STARTED'
export const MULTIGAME_UPDATE_BOARD = '@@CONNECT4/MULTIGAME_UPDATE_BOARD'
export const EXIT_MULTI = '@@CONNECT4/EXIT_MULTI'
